"""Default research implementation.

Milestone 2: real LLM-driven research with live-source fact verification.

Flow (real provider):
  1. Draft — one LLM call returns a structured JSON draft: facts (each citing
     source URLs), top-level sources, angles, entities, chronology, summary.
  2. Fetch & verify — every cited URL is fetched (timeouts + retries); a fact
     is `verified` iff at least one of its sources fetched OK this run. Facts
     with no source reference are dropped as untraceable.
  3. Refine (optional) — a second, non-authoritative LLM pass improves wording
     and flags inconsistencies; it never decides `verified`.

When `llm.name == "stub"`, returns milestone-1 placeholder research so the
demo pipeline keeps working without an API key.

TODO(later milestone): source URLs should come from a dedicated SearchProvider
instead of being generated by the LLM.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import UTC, datetime

from pydantic import ValidationError

from config.settings import ResearchConfig
from core.errors import InputValidationError, StageRetryableError
from core.models import JobContext, StageResult, UserInput
from memory.cache import DiskCache
from providers.base import LLMProvider

from .fetch import SourceFetcher
from .interface import ResearchModule
from .schemas import ResearchFact, ResearchMetadata, ResearchOutput, ResearchSource

log = logging.getLogger(__name__)

CACHE_NAMESPACE = "research"
SCHEMA_VERSION = "v2"  # bump when the research.json shape changes meaningfully


def extract_json(text: str) -> dict:
    """Pull the outermost JSON object out of an LLM response."""
    text = re.sub(r"```(?:json)?", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError("no JSON object found in LLM response")
    return json.loads(text[start : end + 1])


def build_draft_prompt(ui: UserInput) -> str:
    return (
        f"Research the topic: {ui.topic}\n"
        f"Instructions: {', '.join(ui.instructions) or 'none'}\n"
        f"Style: {ui.style or 'default'} | Target duration: {ui.duration or 180}s\n\n"
        'Return a single JSON object (no markdown) with exactly these keys:\n'
        '  "topic": the topic string,\n'
        '  "summary": a 2-3 sentence overview,\n'
        '  "facts": [{"content": str, "sources": ["url", ...], "confidence": 0..1, "verification_note": str|null}] '
        "— 5 to 10 facts,\n"
        '  "sources": [{"url": str, "title": str}] — 4 to 8 authoritative, real URLs,\n'
        '  "angles": [{"title": str, "description": str}] — 2 to 4 interesting angles,\n'
        '  "entities": [{"name": str, "kind": "person|organization|concept|place|product|other"}],\n'
        '  "chronology": [{"date": str, "title": str, "description": str, "sources": ["url"]}] — only when the '
        "topic has a timeline; otherwise [].\n"
        "Rules: every fact.sources entry must appear in the top-level sources list; use real, stable URLs; "
        "keep facts concise and factual."
    )


def placeholder_research(ui: UserInput) -> ResearchOutput:
    topic = ui.topic
    return ResearchOutput(
        topic=topic,
        facts=[
            ResearchFact(content=f"(placeholder) key fact 1 about {topic!r}", sources=["placeholder://source-1"]),
            ResearchFact(content=f"(placeholder) key fact 2 about {topic!r}", sources=["placeholder://source-2"]),
            ResearchFact(content=f"(placeholder) key fact 3 about {topic!r}", sources=["placeholder://source-3"]),
        ],
        sources=[
            ResearchSource(url="https://example.com/placeholder-1", title="Placeholder source 1"),
            ResearchSource(url="https://example.com/placeholder-2", title="Placeholder source 2"),
        ],
        summary=f"(placeholder) Summary of reliable, fact-checked material about {topic!r}.",
        metadata=ResearchMetadata(topic=topic, model="stub", generated_at=datetime.now(UTC).isoformat()),
    )


def collect_urls(output: ResearchOutput, max_urls: int) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for url in [s.url for s in output.sources] + [u for f in output.facts for u in f.sources]:
        if url and url not in seen:
            seen.add(url)
            urls.append(url)
    if len(urls) > max_urls:
        log.warning("capping source fetches at %d URLs (found %d)", max_urls, len(urls))
    return urls[:max_urls]


class DefaultResearchModule(ResearchModule):
    def __init__(
        self,
        llm: LLMProvider,
        cache: DiskCache | None = None,
        config: ResearchConfig | None = None,
    ) -> None:
        self.llm = llm
        self.cache = cache
        self.config = config or ResearchConfig()

    def validate_input(self, ctx: JobContext) -> None:
        if not ctx.input.topic.strip():
            raise InputValidationError("research requires a non-empty topic")

    def run(self, ctx: JobContext) -> StageResult:
        if self.llm.name == "stub":
            output = placeholder_research(ctx.input)
            return StageResult(
                stage=self.name, ok=True, output=output, artifacts_written=[self._save(ctx, "research.json", output)]
            )

        cache_key = f"{SCHEMA_VERSION}:{ctx.input.topic}"
        if self.cache is not None and (cached := self.cache.get(CACHE_NAMESPACE, cache_key)):
            log.info("research: cache hit for %r", ctx.input.topic)
            output = ResearchOutput.model_validate(cached)
            return StageResult(
                stage=self.name, ok=True, output=output, artifacts_written=[self._save(ctx, "research.json", output)]
            )

        output = self._draft(ctx)
        output = self._verify(output, ctx)
        if self.config.refine:
            output = self._refine(output, ctx)
        output.metadata = self._build_metadata(ctx, output)

        if self.cache is not None:
            self.cache.set(CACHE_NAMESPACE, cache_key, output.model_dump(mode="json"))
        return StageResult(
            stage=self.name, ok=True, output=output, artifacts_written=[self._save(ctx, "research.json", output)]
        )

    # -- steps --------------------------------------------------------------

    def _draft(self, ctx: JobContext) -> ResearchOutput:
        system = (
            "You are a research assistant. Return ONLY valid JSON matching the requested schema. "
            "Prefer well-known, authoritative sources with real, stable URLs."
        )
        raw = self.llm.complete(build_draft_prompt(ctx.input), system=system)
        try:
            data = extract_json(raw)
            data["topic"] = data.get("topic") or ctx.input.topic
            return ResearchOutput.model_validate(data)
        except (ValueError, ValidationError) as exc:
            log.warning("research draft parse failed; attempting one repair: %s", exc)
            repair = (
                f"Your previous response was not valid JSON ({exc}). Respond with ONLY valid JSON matching the "
                f"requested schema. Previous response:\n{raw[:2000]}"
            )
            try:
                data = extract_json(self.llm.complete(repair, system=system))
                data["topic"] = data.get("topic") or ctx.input.topic
                return ResearchOutput.model_validate(data)
            except Exception as exc2:  # noqa: BLE001 - surfaced as a retryable stage failure
                raise StageRetryableError(f"research draft not valid JSON after repair: {exc2}") from exc

    def _verify(self, output: ResearchOutput, ctx: JobContext) -> ResearchOutput:
        fetcher = SourceFetcher(
            timeout=self.config.fetch_timeout,
            retries=self.config.fetch_retries,
            max_excerpt_chars=self.config.max_excerpt_chars,
        )
        results = {url: fetcher.fetch(url) for url in collect_urls(output, self.config.max_urls)}
        fetched_ok = {url for url, res in results.items() if res.ok}

        by_url = {source.url: source for source in output.sources}
        accessed_at = datetime.now(UTC).isoformat()
        for url, res in results.items():
            source = by_url.get(url)
            if source is None:
                source = ResearchSource(url=url, title=res.title or url)
                output.sources.append(source)
            source.fetched = res.ok
            source.http_status = res.http_status
            source.excerpt = res.excerpt
            if res.ok:
                source.accessed_at = accessed_at

        kept: list[ResearchFact] = []
        for fact in output.facts:
            if not fact.sources:
                log.info("dropping untraceable fact (no source refs): %.80s", fact.content)
                continue
            fact.verified = any(url in fetched_ok for url in fact.sources)
            if not fact.verified:
                fact.verification_note = "no supporting source fetched successfully"
            kept.append(fact)
        output.facts = kept
        return output

    def _refine(self, output: ResearchOutput, ctx: JobContext) -> ResearchOutput:
        """Non-authoritative polish: tighten wording, flag inconsistencies."""
        facts_json = json.dumps([f.model_dump() for f in output.facts], indent=2)[:6000]
        prompt = (
            f"Here are research facts about {ctx.input.topic!r}.\n"
            'Return ONLY JSON: {"facts": [{"content": str, "verification_note": str|null}]} with one entry per '
            "input fact, in the same order. Keep every fact's meaning; tighten wording; note contradictions or "
            f"unsupported claims in verification_note.\n\nFACTS:\n{facts_json}"
        )
        try:
            data = extract_json(
                self.llm.complete(prompt, system="You polish research facts but are NOT the source of truth.")
            )
            refined = data["facts"]
        except (ValueError, KeyError, ValidationError) as exc:
            log.warning("refine pass failed (%s); keeping draft facts", exc)
            return output
        if len(refined) != len(output.facts):
            log.warning(
                "refine returned %d facts for %d inputs; keeping draft facts", len(refined), len(output.facts)
            )
            return output
        for fact, entry in zip(output.facts, refined, strict=True):
            if entry.get("content"):
                fact.content = entry["content"]
            if entry.get("verification_note"):
                fact.verification_note = entry["verification_note"]
        return output

    def _build_metadata(self, ctx: JobContext, output: ResearchOutput) -> ResearchMetadata:
        fetched = sum(1 for source in output.sources if source.fetched)
        verified = sum(1 for fact in output.facts if fact.verified)
        return ResearchMetadata(
            topic=ctx.input.topic,
            instructions=ctx.input.instructions,
            model=getattr(self.llm, "model", self.llm.name),
            generated_at=datetime.now(UTC).isoformat(),
            fetch_summary=f"{fetched}/{len(output.sources)} sources fetched",
            verification_summary=f"{verified}/{len(output.facts)} facts verified against fetched sources",
            fact_count=len(output.facts),
            source_count=len(output.sources),
        )
